#!/bin/sh
set -e


# Run as current user
if [ ! -z "$ASUSER" ] && [ "$ASUSER" != "0" ]; then
    usermod -u $ASUSER fwd
fi

if [ "$1" = "php-fpm" ]; then
    exec "$@"
else
    exec su-exec fwd "$@"
fi
