#!/bin/sh
set -e

# Run as current user
if [ ! -z "$ASUSER" ] && [ "$ASUSER" != "0" ]; then
    usermod -u $ASUSER developer
fi

if [ "$1" = "php-fpm" ]; then
    exec "$@"
    exit $?
fi

exec su-exec $ASUSER "$@"
