#!/bin/sh
set -e

if [ "$ENABLE_XDEBUG" == "true" ]; then
    docker-php-ext-enable xdebug
fi

# Run as current user
if [ ! -z "$ASUSER" ] && [ "$ASUSER" != "0" ]; then
    usermod -u $ASUSER developer
fi

if [ "$1" = "php-fpm" ]; then
    exec "$@"
else
    exec su-exec developer "$@"
fi
