name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [
          7.1, 7.1-prod, 7.1-wkhtmltopdf, 7.1-wkhtmltopdf-prod,
          7.2, 7.2-prod, 7.2-wkhtmltopdf, 7.2-wkhtmltopdf-prod,
          7.3, 7.3-prod, 7.3-wkhtmltopdf, 7.3-wkhtmltopdf-prod,
          7.4, 7.4-prod, 7.4-wkhtmltopdf, 7.4-wkhtmltopdf-prod,
        ]

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Build image
      run: docker build --pull -t fireworkweb/php:${{ matrix.version }} ${{ matrix.version }}

    - name: Test docker images
      run: |
        docker run fireworkweb/php:${{ matrix.version }} php -v
        docker run fireworkweb/php:${{ matrix.version }} composer -V
        docker run -e ASUSER=1000 fireworkweb/php:${{ matrix.version }} php -v
        docker run -e ASUSER=1000 fireworkweb/php:${{ matrix.version }} composer -V
        docker run fireworkweb/php:${{ matrix.version }} php -m
        docker run -e ENABLE_XDEBUG=true fireworkweb/php:${{ matrix.version }} php -m

        if [[ "${{ matrix.version }}" == *"wkhtmltopdf"* ]]; then
          docker run fireworkweb/php:${{ matrix.version }} wkhtmltopdf -V
          docker run -e ASUSER=1000 fireworkweb/php:${{ matrix.version }} wkhtmltopdf -V
          docker run -e ENABLE_XDEBUG=true fireworkweb/php:${{ matrix.version }} wkhtmltopdf -V
        fi

    - name: Push to Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push fireworkweb/php:${{ matrix.version }}

        if [[ "${{ matrix.version }}" == *"7.4"* ]]; then
          if [[ "${{ matrix.version }}" == *"wkhtmltopdf"* ]]; then
            export MASTER_TAG=$([[ "${{ matrix.version }}" == *"prod"* ]] && echo "wkhtmltopdf-prod" || echo "wkhtmltopdf")
          else
            export MASTER_TAG=$([[ "${{ matrix.version }}" == "7.4-prod" ]] && echo "prod" || echo "latest")
          fi

          docker tag fireworkweb/php:${{ matrix.version }} fireworkweb/php:$MASTER_TAG
          docker push fireworkweb/php:$MASTER_TAG
        fi
